<?php
/**
 * Created by PhpStorm.
 * User: Евгений
 * Date: 25.04.2017
 * Time: 12:43
 */

namespace app\controllers;

use yii\rest\ActiveController;
use yii\helpers\Json;

use app\models\Constant;

use Yii;

class ConstantController extends \yii\rest\ActiveController
{

    public $modelClass = 'app\models\Constant';

    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['create']);
        return $actions;
    }

    public function actionCreate(){
        $model = new Constant();
      
        $res = json_decode(Yii::$app->getRequest()->getRawBody());
        $model->load(Yii::$app->getRequest()->getBodyParams(),'');
        $model->name = $res->name;
        $model->value = $res->value;
        if ($model->save() === false && !$model->hasErrors()) {
            throw new ServerErrorHttpException('Failed to update the object for unknown reason.');
        }
        echo  Json::encode($model);
    }



}