<?php
/**
 * Created by PhpStorm.
 * User: Евгений
 * Date: 25.04.2017
 * Time: 12:43
 */

namespace app\controllers;

use yii\rest\ActiveController;
use yii\helpers\Json;
use app\models\Data;
use app\models\Category;

use Yii;

class DataController extends \yii\rest\ActiveController
{

    public $modelClass = 'app\models\Data';
    public $s_id;
    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['create']);
        return $actions;
    }

    public function actionGetdatabysklad(){
        $this->s_id = $_POST['s_id'];
        $s_id = $_POST['s_id'];
        $s_data = Data::find()->where(array('s_id'=>$s_id))->all();
        echo  Json::encode($s_data);
    }

    public function actionGetdatabyid(){
        $data_id = $_POST['data_id'];
        $s_data = Data::find()->where(array('id'=>$data_id))->all();
        echo  Json::encode($s_data);
    }

    public function actionSetdatabyid(){
        $data_id = (int) $_POST['data_id'];
        $t1 = $_POST['t1'];
        $t2 = $_POST['t2'];
        $t3 = $_POST['t3'];
        $c11 = $_POST['c11'];
        $sup_id = $_POST['selected_sup'];
        $category_name = $_POST['category_name'];

        if ($data_id ==  0){
            $model = new Data();
            $model->sup_id = $sup_id;
            $category = Category::find()->where(array('name'=>$category_name))->one();
            $category_id = $category->id;
            $model->category_id = $category_id;

        }else{
            $model = Data::find()->where(array('id'=>$data_id))->one();
        }

        $model->t1 = $t1;
        $model->t2 = $t2;
        $model->t3 = $t3;
        $model->c11 = $c11;

        if (isset($_POST["s_id"])){ $model->s_id = $_POST["s_id"];}
        $model->save();
        echo  Json::encode($model);
    }

    public function actionGetdatabycategory(){
        $category_name = $_POST['c_name'];
        $this->s_id = $_POST['s_id'];
        $category = Category::find()->where(array('name'=>$category_name))->one();

        $category_id = $category->id;
        $model = Data::find()->where(array('category_id'=>$category_id,'s_id'=>$this->s_id))->all();
        echo  Json::encode($model);
    }

    public function actionDeleteitem(){
        $data_id = $_POST['data_id'];
        $model = Data::deleteAll(array('id'=>$data_id));
        echo  Json::encode($model);
    }

}