<?php
/**
 * Created by PhpStorm.
 * User: Евгений
 * Date: 25.04.2017
 * Time: 12:43
 */

namespace app\controllers;

use yii\rest\ActiveController;

use app\models\Sklad;
use app\models\SkladInfo;
use app\models\Data;
use yii\helpers\Json;

use Yii;

class SkladController extends \yii\rest\ActiveController
{

    public $modelClass = 'app\models\Sklad';

//    public function actions()
//    {
//        $actions =  parent::actions(); // TODO: Change the autogenerated stub
//        unset($actions['create']);
//        return $actions;
//    }

    public function actionGetskladbyid(){
        $s_id = $_POST['s_id'];
     //   $s_id = $_GET['s_id'];
        $model = SkladInfo::find()->where(array('s_id'=>$s_id))->all();
        echo  Json::encode($model);
    }

    public function actionSetskladinfo(){

        $s_id = $_POST['s_id'];
        $s_name = $_POST['s_name'];
        $s_adress = $_POST['s_adress'];

        $sklad = Sklad::find()->where(array('id'=>$s_id))->one();
        $skladInfo = SkladInfo::find()->where(array('s_id'=>$s_id))->one();

        if ($s_id == 0){
            $sklad = new Sklad();
            $skladInfo = new SkladInfo();
            $skladInfo->s_id = $s_adress;
        }

        $sklad->name = $s_name;
        $skladInfo->adress = $s_adress;
        $sklad->save();
        if ($s_id == 0){
            $sklad = Sklad::find()->where(array('name'=>$s_name))->one();
            $skladInfo->s_id = $sklad->id;
        }
        $skladInfo->save();

        echo  Json::encode($skladInfo);
    }

    public function actionDeletesklad(){
        $s_id = $_POST['s_id'];
        $sklad = Sklad::deleteAll(array('id'=>$s_id));
        $sklad_info = SkladInfo::deleteAll(array('s_id'=>$s_id));
        $data = Data::deleteAll(array('s_id'=>$s_id));
        echo  Json::encode($sklad);
    }
}